services:
  - type: web
    name: node-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free

  - type: web
    name: python-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    plan: free